server:
  port: 9094

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: coderef
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write
        resource:
            filter-order: 3

spring:
    datasource:
        password: netinho123
        url: jdbc:postgresql://localhost:5432/oauth
        username: postgres
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: create-drop
        show-sql: true
